create database customer_behavior;
use customer_behavior;
select * from customer_data LIMIT 10;


-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue
from customer_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_data
where discount_applied = "Yes" and
purchase_amount > (select avg(purchase_amount) as avg_purchase_amount
from customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as avg_rating
from customer_data
group by item_purchased
order by avg_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) as purchase_amt
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type;

select * from customer_data LIMIT 10;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_spend
from customer_data
group by subscription_status
order by total_spend, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(sum(
case
	when discount_applied = "Yes"
    then 1 
    else 0
end ) * 100 / 
count(*),2) as discount_rate
from customer_data
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases between 0 and 1 then "New" 
    when previous_purchases between 2 and 10 then "Returning"
    when previous_purchases > 10 then "Loyal"
end as segment
from customer_data)

select segment, count(*) as "Number of customers"
from customer_type
group by segment;

-- Q8. What are the top 3 most purchased products within each category?
select * from (
select category, item_purchased,
count(customer_id) top_purchases,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_data
group by  category, item_purchased) t
where t.item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*)
from customer_data
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;


